export function SourcesPage() {
  return (
    <section className="sources-page">
      <p className="eyebrow">Sources and attribution</p><h1>Academic basis</h1>
      <div className="sources-grid"><article><h2>Primary source</h2><p><cite>forall x: Calgary: A Free and Open Introduction to Formal Logic</cite>, by Aaron Thomas-Bolduc and Richard Zach.</p><p>The current official HTML revision available during implementation was revision 8642250 (2026-07-18). It supplies the terminology, TFL and FOL syntax, truth-table conventions, Fitch rules, interpretations, and rule restrictions used here.</p><p><a href="https://forallx.openlogicproject.org/" target="_blank" rel="noreferrer">Read or download the official textbook ↗</a></p></article><article><h2>License</h2><p>The textbook is licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">Creative Commons Attribution 4.0 ↗</a>.</p><p>Definitions, proof-rule organization, and symbolization patterns identified as “adapted” in the local exercise data are adapted from the textbook. Original prompts and interface explanations were written for Logic Trainer. Changes include restructuring material by topic, concise digital feedback, and deterministic interactive grading.</p></article><article><h2>Configurable convention</h2><p>No PHIL-P 250 syllabus or course rule sheet was present in the workspace. Logic Trainer therefore uses the current Calgary basic rules— including IP as the basic classical rule—and lists DS, MT, DNE, DeM, and LEM as configurable derived rules.</p><p>The rule catalog is data-driven so an instructor’s permitted grouping can be changed without rewriting the proof editor.</p></article></div>
      <div className="source-scope"><h2>Local-first operation</h2><p>The application does not contact the textbook, a grading service, an LLM, or any external API at runtime. Exercises and adapted explanations are stored with the application. Attempts and unfinished-set state remain in this browser’s local storage.</p></div>
    </section>
  )
}
